/*
	GetServiceServiceGate.h
	The interface definition of classes and methods for the ServiceGate web service.
	Generated by SudzC.com
*/
				
#import "Soap.h"
	
/* Add class references */
				

/* Interface for the service */
				
@interface GetServiceServiceGate : SoapService
		
	/* Returns NSString*.  */
	- (SoapRequest*) LogOn: (id <SoapDelegate>) handler profile: (NSString*) profile username: (NSString*) username password: (NSString*) password language: (NSString*) language options: (NSString*) options;
	- (SoapRequest*) LogOn: (id) target action: (SEL) action profile: (NSString*) profile username: (NSString*) username password: (NSString*) password language: (NSString*) language options: (NSString*) options;

	/* Returns NSString*.  */
	- (SoapRequest*) ProcessXml: (id <SoapDelegate>) handler sessionToken: (NSString*) sessionToken inputXml: (NSString*) inputXml;
	- (SoapRequest*) ProcessXml: (id) target action: (SEL) action sessionToken: (NSString*) sessionToken inputXml: (NSString*) inputXml;

	/* Returns NSString*.  */
	- (SoapRequest*) LogOff: (id <SoapDelegate>) handler sessionToken: (NSString*) sessionToken;
	- (SoapRequest*) LogOff: (id) target action: (SEL) action sessionToken: (NSString*) sessionToken;

	/* Returns NSString*.  */
	- (SoapRequest*) KeepAlive: (id <SoapDelegate>) handler sessionToken: (NSString*) sessionToken;
	- (SoapRequest*) KeepAlive: (id) target action: (SEL) action sessionToken: (NSString*) sessionToken;

		
	+ (GetServiceServiceGate*) service;
	+ (GetServiceServiceGate*) serviceWithUsername: (NSString*) username andPassword: (NSString*) password;
@end
	