/*
	GetRedirectData.h
	The interface definition of classes and methods for the Data web service.
	Generated by SudzC.com
*/
				
#import "Soap.h"
	
/* Add class references */
				

/* Interface for the service */
				
@interface GetRedirectData : SoapService
		
	/* Returns NSString*.  */
	- (SoapRequest*) GetInfo: (id <SoapDelegate>) handler myCode: (NSString*) myCode myValue: (NSString*) myValue;
	- (SoapRequest*) GetInfo: (id) target action: (SEL) action myCode: (NSString*) myCode myValue: (NSString*) myValue;

		
	+ (GetRedirectData*) service;
	+ (GetRedirectData*) serviceWithUsername: (NSString*) username andPassword: (NSString*) password;
@end
	